# Generated by Django 3.1.3 on 2020-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='FolderId',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='Position',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='Note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='NumberPeople',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Number of People'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
