# Generated by Django 3.1.3 on 2020-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfileApp', '0002_auto_20201205_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='NumberPeople',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Number of People'),
        ),
    ]
