# Generated by Django 3.1.3 on 2020-12-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfileApp', '0003_auto_20201205_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='NumberPeople',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of People'),
        ),
    ]
