# Generated by Django 3.1.3 on 2020-12-05 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myProfileApp', '0004_auto_20201205_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
