# Generated by Django 3.1.3 on 2020-12-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfileApp', '0005_auto_20201205_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='NumberPeople',
        ),
    ]
