# Generated by Django 3.1.3 on 2020-12-12 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipeApp', '0006_auto_20201210_2209'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myProfileApp', '0006_auto_20201211_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('UserId', 'RecipeId')},
        ),
    ]
