# Generated by Django 3.1.1 on 2020-10-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(default='this is a default info'),
        ),
    ]
