# Generated by Django 3.1.3 on 2020-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('UnitId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique UnitId')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('Abbreviation', models.CharField(max_length=3, verbose_name='Abbreviation')),
            ],
        ),
    ]
