# Generated by Django 3.1.3 on 2020-12-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myNewsletterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUsers',
            new_name='NewsletterUser',
        ),
    ]
