# Generated by Django 3.1.3 on 2020-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique UserId')),
                ('Firstname', models.CharField(default='', max_length=100, verbose_name='Firstname')),
                ('Surname', models.CharField(default='', max_length=100, verbose_name='Surname')),
                ('Nickname', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nickname')),
                ('Email', models.EmailField(default='', max_length=254, verbose_name='Email-Address')),
                ('Password', models.CharField(default='', max_length=50, verbose_name='Password')),
                ('Picture', models.ImageField(blank=True, upload_to='', verbose_name='Profile Picture')),
                ('Status', models.CharField(choices=[('ACT', 'Active'), ('NEW', 'New'), ('LOC', 'Locked'), ('DEL', 'Deleted')], default='NEW', max_length=3, verbose_name='Status')),
                ('LastLogin', models.DateTimeField(auto_now=True, verbose_name='Last Login Date')),
                ('RetryLogin', models.PositiveSmallIntegerField(default=0, verbose_name='Number of Login Attempts')),
            ],
        ),
    ]
