# Generated by Django 3.1.3 on 2020-12-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfileApp', '0005_auto_20201205_1435'),
        ('myRecipeApp', '0004_auto_20201205_1435'),
        ('myLoginApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
