# Generated by Django 3.1.3 on 2020-11-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginApp', '0002_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='*', max_length=254, verbose_name='EMail-Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default='*', max_length=100, verbose_name='Firstname'),
        ),
        migrations.AddField(
            model_name='user',
            name='LastLogin',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Login Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='Nickname',
            field=models.CharField(default='*', max_length=100, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='*', max_length=50, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='Picture',
            field=models.ImageField(default='', upload_to='', verbose_name='UserPicture'),
        ),
        migrations.AddField(
            model_name='user',
            name='RetryLogin',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of Login Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('ACT', 'Active'), ('NEW', 'New'), ('LOC', 'Locked'), ('DEL', 'Deleted')], default='NEW', max_length=3, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='Surname',
            field=models.CharField(default='*', max_length=100, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='user',
            name='UserId',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False, verbose_name='Unique UserId'),
        ),
    ]
