# Generated by Django 3.1.3 on 2020-12-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginApp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='upload/', verbose_name='Profile Picture'),
        ),
    ]
