# Generated by Django 3.1.3 on 2020-11-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginApp', '0003_auto_20201129_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email-Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Firstname',
            field=models.CharField(default='', max_length=100, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Nickname',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Surname',
            field=models.CharField(default='', max_length=100, verbose_name='Surname'),
        ),
    ]
