# Generated by Django 3.1.3 on 2020-11-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginApp', '0005_auto_20201129_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique UserId'),
        ),
    ]
