# Generated by Django 3.1.3 on 2020-11-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myUnitApp', '0001_initial'),
        ('myLoginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique CategoryId')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('FoodItemId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique FoodItemId')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique RecipeId')),
                ('RecipeName', models.CharField(max_length=300, verbose_name='Recipe Name')),
                ('Picture', models.ImageField(upload_to='', verbose_name='Recipe Picture')),
                ('Energy', models.PositiveIntegerField(verbose_name='Calories')),
                ('NumberPeople', models.PositiveSmallIntegerField(verbose_name='Number of People')),
                ('UnitId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myUnitApp.unit', verbose_name='Unit of Energy')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myLoginApp.user', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('RatingId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique RecipeStepId')),
                ('Duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duration in Minutes')),
                ('StepNo', models.PositiveSmallIntegerField(verbose_name='Step Number')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Tips', models.TextField(blank=True, verbose_name='Tips')),
                ('RecipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myRecipeApp.recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('RecipeCategoryId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique RecipeCategoryId')),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myRecipeApp.category', verbose_name='Category')),
                ('RecipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myRecipeApp.recipe', verbose_name='Recipe')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myLoginApp.user', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('RatingId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique RatingId')),
                ('Comment', models.TextField(blank=True, verbose_name='Comment')),
                ('Scale', models.PositiveSmallIntegerField(blank=True, verbose_name='Star Rating')),
                ('DateTime', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('Visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLoginApp.user', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('IngredientId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unique UnitId')),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('Note', models.TextField(verbose_name='Note')),
                ('FoodItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myRecipeApp.fooditem', verbose_name='Food Item')),
                ('UnitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUnitApp.unit', verbose_name='Unit')),
            ],
        ),
    ]
