# Generated by Django 3.1.3 on 2020-11-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myUnitApp', '0001_initial'),
        ('myRecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='UnitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUnitApp.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='UnitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myUnitApp.unit', verbose_name='Unit of Energy'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
