# Generated by Django 3.1.3 on 2020-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Recipe Picture'),
        ),
    ]
