# Generated by Django 3.1.3 on 2020-11-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipeApp', '0002_auto_20201129_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='FolderIdParent',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
