# Generated by Django 3.1.3 on 2020-12-09 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipeApp', '0004_auto_20201205_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='RecipeId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myRecipeApp.recipe', verbose_name='Recipe'),
        ),
    ]
