# Generated by Django 3.1.3 on 2020-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipeApp', '0005_ingredient_recipeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='Note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Energy',
            field=models.PositiveIntegerField(blank=True, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='NumberPeople',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Number of People'),
        ),
    ]
