# Generated by Django 3.1.1 on 2020-12-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecipeApp', '0007_recipecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='upload/', verbose_name='Recipe Picture'),
        ),
    ]
